name : Elso workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp
      - run: ./run_test.sh
      - run: diff output.txt good_output.txt