name : Elso workflow

on:
  push

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp -o gcd
      - run: ./run_test.sh gcd output.txt
      - run: diff output.txt good_output.txt