name : Elso workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: g++ -Wall main.cpp
      - run: IFS=$'\n'; for i in `cat input.txt`; do echo "$i" | ./a.out; done